### ISSUE TITLE
BSAPI-11: Retrieve List of Books by Genre (BB&S - 1)

### ISSUE THREAD

**Issue by mibal001** [Software-Engineering-1-Group-13/Bookstore-API#23]
### Summary
Given a specific genre, return a list of books in the genre. Also implement a genre to the book class. 

### Rationale
- **Motivation**: To be able to sort by genre. It should improve the user's experience using the book store. 
- **Functionality**: Adds a genre to the book class. Allows users to be able to sort by genre of book. 
- **Impact**: It will affect the book class and probably a new class where the different types of search functions can be implemented. 
### Acceptance Criteria
- A GET request that works on genres.
- Returns a JSON list of books

### Acceptance Test Cases:
- Be able to sort by genre given an empty genre input
- Be able to deal with an input that has typos in it
- Be able to sort by genre given the user input the genre correctly

**Comment by IvanoskiHarmonia** [comment]
1.  In the `Acceptance Criteria` fix the additional indentation on the second list point.
2. Try to specify what API call you have to do (any API calls need to be in all uppercase like GET, POST, PUT, DELETE)
3. Try to start with an uppercase letter in every new line
4. You can practically split up the acceptance test case into 3 since they are different list points.
5. Don't forget to add this issue to the current spring project.
6. Don't forget to set the milestone we have.
7. I would not say this will take you an hour of work, but you can decide that.
